#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status.
set -e

# Decide which docker-compose file to use
COMPOSE_FILE="dev"

COMPOSE="docker-compose -f docker-compose.base.yml -f docker-compose.$COMPOSE_FILE.yml"

if [ $# -gt 0 ]; then
    # install development env
    if [ "$1" == "install" ]; then
        shift 1

        if [ ! -d "html/" ] || [ -z "$(ls -A html/)" ]; then
            if [ ! -d "html/" ]; then
                mkdir "html/" > /dev/null
            fi
            ./develop composer create-project --no-scripts --prefer-dist laravel/laravel .
            rm html/.env*
        else
            ./develop composer install
        fi

        ./develop npm install

    elif [ "$1" == "start" ]; then
        shift 1
        ./develop up -d

    elif [ "$1" == "stop" ]; then
        shift 1
        ./develop down

    elif [ "$1" == "log" ]; then
        shift 1
        $COMPOSE exec \
            -w /var/www/html \
            app \
            tail storage/logs/laravel.log "$@"

    elif [ "$1" == "art" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            app \
            php artisan "$@"

    elif [ "$1" == "composer" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            app \
            composer "$@"

    elif [ "$1" == "test" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            app \
            ./vendor/bin/phpunit "$@"

    elif [ "$1" == "t" ]; then
        shift 1
        ./develop test "$@"

    elif [ "$1" == "npm" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            node \
            npm "$@"
    else
        $COMPOSE "$@"
    fi
else
    $COMPOSE ps
fi
