-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 10:22:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema couponpocket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema couponpocket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `couponpocket` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `couponpocket` ;

-- -----------------------------------------------------
-- Table `couponpocket`.`coupon_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `couponpocket`.`coupon_categories` ;

CREATE TABLE IF NOT EXISTS `couponpocket`.`coupon_categories` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `color_background` VARCHAR(7) NOT NULL,
  `color_foreground` VARCHAR(7) NOT NULL,
  `code_type` INT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `couponpocket`.`coupons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `couponpocket`.`coupons` ;

CREATE TABLE IF NOT EXISTS `couponpocket`.`coupons` (
  `id` VARCHAR(36) NOT NULL,
  `points` VARCHAR(255) NOT NULL,
  `condition` VARCHAR(255) NOT NULL,
  `ean` VARCHAR(255) NOT NULL,
  `source` VARCHAR(255) NULL,
  `valid_from` DATE NULL,
  `valid_till` DATE NULL,
  `visibility` INT NOT NULL DEFAULT 0,
  `coupon_category_id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `ean`),
  INDEX `fk_coupons_coupon_categories_idx` (`coupon_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_coupons_coupon_categories`
    FOREIGN KEY (`coupon_category_id`)
    REFERENCES `couponpocket`.`coupon_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `couponpocket`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `couponpocket`.`users` ;

CREATE TABLE IF NOT EXISTS `couponpocket`.`users` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` TINYINT UNSIGNED NOT NULL DEFAULT 4,
  `remember_token` VARCHAR(100) NULL,
  `email_verified_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `couponpocket`.`failed_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `couponpocket`.`failed_jobs` ;

CREATE TABLE IF NOT EXISTS `couponpocket`.`failed_jobs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `couponpocket`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `couponpocket`.`migrations` ;

CREATE TABLE IF NOT EXISTS `couponpocket`.`migrations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `couponpocket`.`personal_access_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `couponpocket`.`personal_access_tokens` ;

CREATE TABLE IF NOT EXISTS `couponpocket`.`personal_access_tokens` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` VARCHAR(255) NOT NULL,
  `tokenable_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `abilities` TEXT NULL,
  `last_used_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `index2` (`tokenable_type` ASC) VISIBLE,
  UNIQUE INDEX `index3` (`token` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `couponpocket`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `couponpocket`.`password_resets` ;

CREATE TABLE IF NOT EXISTS `couponpocket`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `couponpocket`.`card_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `couponpocket`.`card_types` ;

CREATE TABLE IF NOT EXISTS `couponpocket`.`card_types` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NULL,
  `coupon_category_id` VARCHAR(36) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_card_types_coupon_categories1_idx` (`coupon_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_card_types_coupon_categories1`
    FOREIGN KEY (`coupon_category_id`)
    REFERENCES `couponpocket`.`coupon_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `couponpocket`.`cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `couponpocket`.`cards` ;

CREATE TABLE IF NOT EXISTS `couponpocket`.`cards` (
  `id` VARCHAR(36) NOT NULL,
  `number` BIGINT NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `card_type_id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cards_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_cards_card_types1_idx` (`card_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_cards_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `couponpocket`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cards_card_types1`
    FOREIGN KEY (`card_type_id`)
    REFERENCES `couponpocket`.`card_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `couponpocket`.`coupon_categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `couponpocket`;
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `color_background`, `color_foreground`, `code_type`, `created_at`, `updated_at`, `deleted_at`) VALUES ('f22959ea-81be-43fd-aba6-d659953c50d9', 'REWE', '#CC071E', '#FFFFFF', 1, DEFAULT, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `color_background`, `color_foreground`, `code_type`, `created_at`, `updated_at`, `deleted_at`) VALUES ('9e06c83a-d28d-4181-84c1-ee2bc260ff8c', 'dm', '#F6F6F7', '#1C3277', 1,  DEFAULT, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `color_background`, `color_foreground`, `code_type`, `created_at`, `updated_at`, `deleted_at`) VALUES ('f678fa75-d004-49dd-a726-016c6128bb68', 'Penny', '#CD1414', '#FFFFFF', 1,  DEFAULT, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `color_background`, `color_foreground`, `code_type`, `created_at`, `updated_at`, `deleted_at`) VALUES ('064da2f9-4b0b-4cec-ba44-699960756b0f', 'real', '#EFE6DF', '#183C6C', 1,  DEFAULT, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `color_background`, `color_foreground`, `code_type`, `created_at`, `updated_at`, `deleted_at`) VALUES ('b33435c2-4f08-43bb-aca9-3a60764143c0', 'ARAL', '#009EE0', '#FFFFFF', 2,  DEFAULT, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `color_background`, `color_foreground`, `code_type`, `created_at`, `updated_at`, `deleted_at`) VALUES ('54b12eba-1431-4149-8808-d66a5a5035cf', 'FRESSNAPF', '#196428', '#FFFFFF', 2,  DEFAULT, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `color_background`, `color_foreground`, `code_type`, `created_at`, `updated_at`, `deleted_at`) VALUES ('3605c937-fd47-4c56-bf51-3f47f0b99102', 'WMF', '#FFFFFF', '#000000', 1,  DEFAULT, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `color_background`, `color_foreground`, `code_type`, `created_at`, `updated_at`, `deleted_at`) VALUES ('0d924886-7116-4fa1-a3ef-6f0f03ac03a4', 'DEPOT', '#FFFFFF', '#053841', 2,  DEFAULT, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `color_background`, `color_foreground`, `code_type`, `created_at`, `updated_at`, `deleted_at`) VALUES ('08f7d59e-f921-465b-a162-194880dfcb2f', 'Burger King', '#FFFFFF', '#D62300', 3,  DEFAULT, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `color_background`, `color_foreground`, `code_type`, `created_at`, `updated_at`, `deleted_at`) VALUES ('a449ca47-ed5b-4744-be2c-6177fe0910d3', 'Thalia', '#FFFFFF', '#1A1AAA', 2,  DEFAULT, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `color_background`, `color_foreground`, `code_type`, `created_at`, `updated_at`, `deleted_at`) VALUES ('dd6d6e12-842f-49de-b374-2ad468e144b6', 'Globus', '#00622C', '#F47920', 2,  DEFAULT, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `color_background`, `color_foreground`, `code_type`, `created_at`, `updated_at`, `deleted_at`) VALUES ('e9eb7907-22ad-48fc-81cf-d094b25a08be', 'C&A', '#FFFFFF', '#000000', 1,  DEFAULT, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `couponpocket`.`migrations`
-- -----------------------------------------------------
START TRANSACTION;
USE `couponpocket`;
INSERT INTO `couponpocket`.`migrations` (`id`, `migration`, `batch`) VALUES (1, '2019_08_19_000000_create_failed_jobs_table', 1);
INSERT INTO `couponpocket`.`migrations` (`id`, `migration`, `batch`) VALUES (2, '2019_12_14_000001_create_personal_access_tokens_table', 1);
INSERT INTO `couponpocket`.`migrations` (`id`, `migration`, `batch`) VALUES (3, '2022_02_24_083542_create_password_resets_table', 1);
INSERT INTO `couponpocket`.`migrations` (`id`, `migration`, `batch`) VALUES (4, '2022_03_02_170830_create_users_table', 1);
INSERT INTO `couponpocket`.`migrations` (`id`, `migration`, `batch`) VALUES (5, '2023_03_06_123140_changed_id_from_int_to_uuid_for_coupons_and_categories', 1);
INSERT INTO `couponpocket`.`migrations` (`id`, `migration`, `batch`) VALUES (6, '2023_03_06_141749_add_code_style_to_coupon_categories', 1);
INSERT INTO `couponpocket`.`migrations` (`id`, `migration`, `batch`) VALUES (7, '2023_03_11_112532_add_card_types_and_cards', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `couponpocket`.`card_types`
-- -----------------------------------------------------
START TRANSACTION;
USE `couponpocket`;
INSERT INTO `couponpocket`.`card_types` (`id`, `name`, `coupon_category_id`, `created_at`, `updated_at`, `deleted_at`) VALUES ('cedf2154-67bb-471c-b92a-dba3e6ec5559', 'Payback', NULL, DEFAULT, NULL, NULL);
INSERT INTO `couponpocket`.`card_types` (`id`, `name`, `coupon_category_id`, `created_at`, `updated_at`, `deleted_at`) VALUES ('bb5140c3-af2e-4b76-8053-a57db881b4ab', 'REWE Treuepunkte', 'f22959ea-81be-43fd-aba6-d659953c50d9', DEFAULT, NULL, NULL);
INSERT INTO `couponpocket`.`card_types` (`id`, `name`, `coupon_category_id`, `created_at`, `updated_at`, `deleted_at`) VALUES ('ea66ecfe-d9c8-4849-8cac-d6e3ad4a910d', 'REWE Coupons', 'f22959ea-81be-43fd-aba6-d659953c50d9', DEFAULT, NULL, NULL);
INSERT INTO `couponpocket`.`card_types` (`id`, `name`, `coupon_category_id`, `created_at`, `updated_at`, `deleted_at`) VALUES ('9aa0f516-ed1c-4a6f-b63c-86ea8427115f', 'Fressnapf', '54b12eba-1431-4149-8808-d66a5a5035cf', DEFAULT, NULL, NULL);

COMMIT;

