-- MySQL Script generated by MySQL Workbench
-- Sat Mar 13 17:37:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema couponpocket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema couponpocket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `couponpocket` DEFAULT CHARACTER SET utf8 ;
USE `couponpocket` ;

-- -----------------------------------------------------
-- Table `couponpocket`.`coupon_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `couponpocket`.`coupon_categories` ;

CREATE TABLE IF NOT EXISTS `couponpocket`.`coupon_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `logo` TEXT NOT NULL,
  `color` VARCHAR(7) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `couponpocket`.`coupons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `couponpocket`.`coupons` ;

CREATE TABLE IF NOT EXISTS `couponpocket`.`coupons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `points` VARCHAR(255) NOT NULL,
  `condition` VARCHAR(255) NOT NULL,
  `ean` VARCHAR(255) NOT NULL,
  `source` VARCHAR(255) NULL,
  `valid_from` DATETIME NULL,
  `valid_till` DATETIME NULL,
  `coupon_category_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `ean`),
  INDEX `fk_coupons_coupon_categories_idx` (`coupon_category_id` ASC),
  CONSTRAINT `fk_coupons_coupon_categories`
    FOREIGN KEY (`coupon_category_id`)
    REFERENCES `couponpocket`.`coupon_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `couponpocket`.`coupon_categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `couponpocket`;
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `logo`, `color`, `created_at`, `updated_at`, `deleted_at`) VALUES (DEFAULT, 'Rewe', 'rewe.svg', '#CC071E', NULL, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `logo`, `color`, `created_at`, `updated_at`, `deleted_at`) VALUES (DEFAULT, 'DM', 'dm.svg', '#F6F6F7', NULL, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `logo`, `color`, `created_at`, `updated_at`, `deleted_at`) VALUES (DEFAULT, 'Penny', 'penny.svg', '#CD1414', NULL, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `logo`, `color`, `created_at`, `updated_at`, `deleted_at`) VALUES (DEFAULT, 'Real', 'real.svg', '#FFFFFF', NULL, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `logo`, `color`, `created_at`, `updated_at`, `deleted_at`) VALUES (DEFAULT, 'Aral', 'aral.svg', '#009EE0', NULL, NULL, NULL);
INSERT INTO `couponpocket`.`coupon_categories` (`id`, `name`, `logo`, `color`, `created_at`, `updated_at`, `deleted_at`) VALUES (DEFAULT, 'Fressnapf', 'fressnapf.svg', '#FFFFFF', NULL, NULL, NULL);

COMMIT;

